---
### Try to open the Corpus

In [147]:
with open('data/wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
print(text[:200])

  DOROTHY AND THE WIZARD IN OZ

  BY

  L. FRANK BAUM

  AUTHOR OF THE WIZARD OF OZ, THE LAND OF OZ, OZMA OF OZ, ETC.

  ILLUSTRATED BY JOHN R. NEILL

  BOOKS OF WONDER WILLIAM MORROW & CO., INC. NEW


In [148]:
with open('wizard_of_oz.txt') as f:
    text = f.read()
print(text[:200])

  DOROTHY AND THE WIZARD IN OZ

  BY

  L. FRANK BAUM

  AUTHOR OF THE WIZARD OF OZ, THE LAND OF OZ, OZMA OF OZ, ETC.

  ILLUSTRATED BY JOHN R. NEILL

  BOOKS OF WONDER WILLIAM MORROW & CO., INC. NEW


--- 
### To process the chars / diff. way to format output length

If you try to sort all the characters, some might duplicate,
therefore use a `set` to remove the duplication

In [149]:
with open('wizard_of_oz.txt', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
print(chars)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


#### or use pprint to look at what charcters are there in the corpus

In [150]:
from pprint import pprint

pprint(chars, width=80)

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '\ufeff']


In [151]:
# Wrap characters into a string with line breaks every 50 chars
chars = sorted(set(text))
joined = ''.join(chars)

# Break into multiple lines for readability
for i in range(0, len(joined), 50):
    print(joined[i:i+50])



 !"&'()*,-.0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWXY
Z[]_abcdefghijklmnopqrstuvwxyz


In [152]:
from IPython.display import display

display(sorted(set(text)))


['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 ...]

In [153]:
from IPython import get_ipython

ip = get_ipython()
ip.display_formatter.formatters['text/plain'].max_seq_length = 30  # Wrap after 30 items

print(sorted(set(text)))


['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


#### Write my own print formatting for jupyter notebook cell

In [154]:
chars = sorted(set(text))

def aprint(chars, chars_per_line=12):
    for i in range(0, len(chars), chars_per_line):
        print(chars[i:i+chars_per_line])
        
aprint(chars)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.']
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';']
['?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K']
['L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W']
['X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f']
['g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r']
['s', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


---

In [155]:
string_to_int = {c: i for i, c in enumerate(chars)}
print(string_to_int)

string_to_int['&']

{'\n': 0, ' ': 1, '!': 2, '"': 3, '&': 4, "'": 5, '(': 6, ')': 7, '*': 8, ',': 9, '-': 10, '.': 11, '0': 12, '1': 13, '2': 14, '3': 15, '4': 16, '5': 17, '6': 18, '7': 19, '8': 20, '9': 21, ':': 22, ';': 23, '?': 24, 'A': 25, 'B': 26, 'C': 27, 'D': 28, 'E': 29, 'F': 30, 'G': 31, 'H': 32, 'I': 33, 'J': 34, 'K': 35, 'L': 36, 'M': 37, 'N': 38, 'O': 39, 'P': 40, 'Q': 41, 'R': 42, 'S': 43, 'T': 44, 'U': 45, 'V': 46, 'W': 47, 'X': 48, 'Y': 49, 'Z': 50, '[': 51, ']': 52, '_': 53, 'a': 54, 'b': 55, 'c': 56, 'd': 57, 'e': 58, 'f': 59, 'g': 60, 'h': 61, 'i': 62, 'j': 63, 'k': 64, 'l': 65, 'm': 66, 'n': 67, 'o': 68, 'p': 69, 'q': 70, 'r': 71, 's': 72, 't': 73, 'u': 74, 'v': 75, 'w': 76, 'x': 77, 'y': 78, 'z': 79, '\ufeff': 80}


4

In [156]:
int_to_string = {i: c for c, i in string_to_int.items()}
print(int_to_string)

int_to_string[4]

{0: '\n', 1: ' ', 2: '!', 3: '"', 4: '&', 5: "'", 6: '(', 7: ')', 8: '*', 9: ',', 10: '-', 11: '.', 12: '0', 13: '1', 14: '2', 15: '3', 16: '4', 17: '5', 18: '6', 19: '7', 20: '8', 21: '9', 22: ':', 23: ';', 24: '?', 25: 'A', 26: 'B', 27: 'C', 28: 'D', 29: 'E', 30: 'F', 31: 'G', 32: 'H', 33: 'I', 34: 'J', 35: 'K', 36: 'L', 37: 'M', 38: 'N', 39: 'O', 40: 'P', 41: 'Q', 42: 'R', 43: 'S', 44: 'T', 45: 'U', 46: 'V', 47: 'W', 48: 'X', 49: 'Y', 50: 'Z', 51: '[', 52: ']', 53: '_', 54: 'a', 55: 'b', 56: 'c', 57: 'd', 58: 'e', 59: 'f', 60: 'g', 61: 'h', 62: 'i', 63: 'j', 64: 'k', 65: 'l', 66: 'm', 67: 'n', 68: 'o', 69: 'p', 70: 'q', 71: 'r', 72: 's', 73: 't', 74: 'u', 75: 'v', 76: 'w', 77: 'x', 78: 'y', 79: 'z', 80: '\ufeff'}


'&'

In [157]:
encode = lambda s: [ string_to_int[c] for c in s ]

encode('hello')

[61, 58, 65, 65, 68]

In [158]:
decode = lambda l: ''.join([ int_to_string[i] for i in l ])

decode(encode('hello'))

'hello'

#### put it all together

In [159]:
string_to_int = {ch: i for i, ch in enumerate(set(text))}
int_to_string = {i: ch for ch, i in string_to_int.items()}
encode = lambda s: [string_to_int[ch] for ch in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

In [160]:
encode('hello')

[16, 6, 77, 77, 62]

In [161]:
encoded_hello = encode('hello')
decoded_hello = decode(encoded_hello)

print(encoded_hello, decoded_hello)

[16, 6, 77, 77, 62] hello


### Some background information of these tokenizers

- right now, we're using the character level tokenizer, which converting each character into integer
- so we have `a small vocabulary` (characters as vocabulary), and a very large amount of `tokens` to convert. We have `40,000` individual characters -- we have a small vocabulary to work with
- if we work with a word-level tokenizer, every single words in English, that means we have a TON, like every single word in English language, and worse if you have multiple languages.
- It's millions or trillions if you're doing something wiered. In this case, the tokenizer vocabulary are huge, but way smaller set to work with. (Very large vocabulary, very small to encode/decode)
- if you are a `sub-word` tokenizer - that means you are some way in between.

---
### Change every data into `pytorch` or `torch` as `tensors`

In [162]:
import torch

# For MAC, the GPU is MPS
device = 'mps' if torch.backends.mps.is_available() else 'cpu'
print(f'Device is: {device}')

with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    

chars = sorted(set(text))
print(chars)
vocabulary_size = len(chars)
print(f'vocabulary_size = {vocabulary_size}')


int_to_char = {i: ch for i, ch in enumerate(chars)}
char_to_int = {ch: i for i, ch in enumerate(chars)}
encode = lambda s: [char_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_char[i] for i in l])

Device is: mps
['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']
vocabulary_size = 81


In [163]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])

torch.Size([232309]) torch.int64
tensor([80,  1,  1, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,
         1, 47, 33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26,
        49,  0,  0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,
         0,  0,  1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1,
        47, 33, 50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1,
        36, 25, 38, 28,  1, 39, 30,  1, 39, 50])


---
### Validation and Training Splits

> - Why we just don't use the entire document/text and only train on that?
> - The reason we split into train and validation sets,..(later)

In [164]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

In [165]:
print(train_data.size(),  val_data.size())

torch.Size([185847]) torch.Size([46462])


---

In [166]:
block_size = 8

# this is like a sliding window, where we take 8 chars at a time
x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f'when input is {context} the target is: {target}')

when input is tensor([80]) the target is: 1
when input is tensor([80,  1]) the target is: 1
when input is tensor([80,  1,  1]) the target is: 28
when input is tensor([80,  1,  1, 28]) the target is: 39
when input is tensor([80,  1,  1, 28, 39]) the target is: 42
when input is tensor([80,  1,  1, 28, 39, 42]) the target is: 39
when input is tensor([80,  1,  1, 28, 39, 42, 39]) the target is: 44
when input is tensor([80,  1,  1, 28, 39, 42, 39, 44]) the target is: 32


---
###  Some experiments about torch's matrix

In [167]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 82,  31,  46,  43,  -8, -15])

Create a 2 x 3 tensor

In [168]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [169]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [170]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [171]:
input = torch.empty(2, 3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [172]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [173]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [174]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [175]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [176]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

---
### Experiments with `time`

In [177]:
block_size = 8
batch_size = 4  # how many blocks we're doing in parallel

In [178]:
import torch
import numpy as np
import time

device = 'mps' if torch.backends.mps.is_available() else 'cpu'
print(f'Device is: {device}')

Device is: mps


In [179]:
start_time = time.time()
start_time

1745288254.388303

In [180]:
start_time = time.time()
zeros = torch.zeros(1, 1)
end_time = time.time()

elapse_time = end_time - start_time
print(f"elapse_time = {elapse_time:.8f}")

elapse_time = 0.00022507


#### 🐙 Comparing `time` for GPU vs CPU (with torch vs numpy matrix multiplication)

In [181]:
start_time = time.time()
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand1
end_time = time.time()
print(f"elapsed_time = {end_time - start_time:.8f}")

elapsed_time = 4.59506989


In [182]:
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"elapse_time = {elapsed_time:.8f}")

elapse_time = 0.00842094


In [183]:
star_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"elapsed_time: {elapsed_time:.8f}")

elapsed_time: 0.26568413


/var/folders/01/2j7mx2qs27j6cjvfw8cs8ps80000gn/T/ipykernel_60329/1483514504.py:3: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [184]:
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)  # these causes complaints about deprecation 
np_rand2 = torch.rand(10000, 10000)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"elapse_time = {elapsed_time:.8f}")

star_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"elapsed_time = {elapsed_time:.8f}")

elapse_time = 0.01720190
elapsed_time = 0.08940887


/var/folders/01/2j7mx2qs27j6cjvfw8cs8ps80000gn/T/ipykernel_60329/2434095031.py:17: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [185]:
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000).numpy()  # no more complains
np_rand2 = torch.rand(10000, 10000).numpy()

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"elapse_time = {elapsed_time:.8f}")

star_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"elapsed_time = {elapsed_time:.8f}")

elapse_time = 0.01474571
elapsed_time = 0.11285996


##### 🌳 lets create more dimensions for tensor and numpy to compare

In [186]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100).numpy()
np_rand2 = torch.rand(100, 100, 100, 100).numpy()

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"elapse_time = {elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"elapsed_time = {elapsed_time:.8f}")

elapse_time = 0.01447082
elapsed_time = 0.07774997


## 🔑 What went `WRONG` since GPU seems slower than CPU?

 ### Something **isn't quite right** in our codes above and results.
---

### 🔍 1. **Biggest Issue: `@` operator on 4D tensors is undefined!**

```python
rand = (torch_rand1 @ torch_rand2)
```

This line is **invalid math**: the `@` (matrix multiplication) operator is **defined only for 2D (matrices)** or **batched 3D tensors**.

Our tensors are shape **`(100, 100, 100, 100)`** — so `@` might **not even be doing what you think**. It could raise an error in newer PyTorch or behave unexpectedly (and slowly).

---

#### ✅ Fix it: Use `torch.matmul` explicitly and reshape

If we want to test **matrix multiplication** speed, we'll need **2D or batch matrix multiply**. For example:

```python
# Reduce shape to valid matmul: (10000, 10000)
A = torch.rand(10000, 10000, device=device)
B = torch.rand(10000, 10000, device=device)

start = time.time()
C = A @ B
torch.cuda.synchronize() if device == 'cuda' else None
end = time.time()
print(f"GPU matmul time: {end - start:.6f}")
```

---

### 🔥 2. **Missing GPU Sync**

In our original GPU code:

```python
start_time = time.time()
rand = torch_rand1 @ torch_rand2
end_time = time.time()
```

GPU operations are **asynchronous** by default, so `end_time` might be recorded before the GPU actually finishes computation.

#### ✅ Fix it: Add `torch.cuda.synchronize()`

```python
start_time = time.time()
rand = torch_rand1 @ torch_rand2
torch.cuda.synchronize()  # Wait for GPU to finish
end_time = time.time()
```

For M1/M2 macs (Apple Silicon):
```python
torch.mps.synchronize()
```

---

### ⚠️ 3. **NumPy tensors are NOT NumPy!**

This is dangerous:

```python
np_rand1 = torch.rand(...).numpy()
```

We're converting **PyTorch tensors to NumPy** using `.numpy()`, but **only works if on CPU**.

If they're still on GPU (or MPS), this will error or give wrong result.

#### ✅ Fix:

```python
np_rand1 = torch.rand(100, 100).cpu().numpy()
```

---

### ✅ Final Cleaned Version: Proper GPU vs CPU benchmark

```python
import torch
import time
import numpy as np

device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
print("Using device:", device)

# Use 2D matrix for fair test
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)

# GPU test
start = time.time()
rand = torch_rand1 @ torch_rand2
if device == "cuda":
    torch.cuda.synchronize()
elif device == "mps":
    torch.mps.synchronize()
end = time.time()
print(f"GPU matmul time = {end - start:.6f} sec")

# CPU NumPy test (element-wise mult)
np_rand1 = torch.rand(10000, 10000).cpu().numpy()
np_rand2 = torch.rand(10000, 10000).cpu().numpy()

start = time.time()
rand = np.multiply(np_rand1, np_rand2)
end = time.time()
print(f"CPU np.multiply time = {end - start:.6f} sec")
```

---

### 🧠 Summary

| Problem                         | Fix                                                       |
|----------------------------------|------------------------------------------------------------|
| ❌ Invalid `@` for 4D tensors     | ✅ Use 2D or batched 3D with `@` or `matmul`                |
| ❌ No GPU sync                   | ✅ Add `torch.cuda.synchronize()` before timing ends       |
| ❌ NumPy from GPU tensor         | ✅ Move to CPU with `.cpu().numpy()`                       |

---

We may also like to also compare `torch.mul()` vs `np.multiply()` or include `cupy` as a GPU-accelerated NumPy alternative. We'll explore later.

In [187]:
import torch
import time
import numpy as np

device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
print("Using device:", device)

# Use 2D matrix for fair test
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)

# GPU test
start = time.time()
rand = torch_rand1 @ torch_rand2
if device == "cuda":
    torch.cuda.synchronize()
elif device == "mps":
    torch.mps.synchronize()
end = time.time()
print(f"GPU matmul time = {end - start:.6f} sec")

# CPU NumPy test (element-wise mult)
np_rand1 = torch.rand(10000, 10000).cpu().numpy()
np_rand2 = torch.rand(10000, 10000).cpu().numpy()

start = time.time()
rand = np.multiply(np_rand1, np_rand2)
end = time.time()
print(f"CPU np.multiply time = {end - start:.6f} sec")


Using device: mps
GPU matmul time = 0.820652 sec
CPU np.multiply time = 0.082828 sec


### 🔑 still seems wrong, what happened (`unfair benchmark`)

## 🧨 The core issue:
we're comparing **two *fundamentally different operations***:

| Operation                        | What it does                                  | Complexity |
|----------------------------------|-----------------------------------------------|------------|
| `@` or `matmul` (on GPU)         | **Matrix multiplication**: `A @ B`            | **O(n³)**   |
| `np.multiply` (on CPU)           | **Element-wise multiplication**: `A * B`      | **O(n)**    |


> ❗ we're comparing **heavy matrix math** vs **lightweight point-wise math** — they’re not meant to take equal time.

---

## ✅ Let’s make it a *fair benchmark*

We’ll compare **the same operation** across **CPU vs GPU**:

### 🧪 A. Matrix Multiplication: GPU vs CPU

```python
import torch
import time

size = 4000  # careful! 10000 x 10000 may crash CPU RAM

A_cpu = torch.rand(size, size)
B_cpu = torch.rand(size, size)

# CPU matmul
start = time.time()
result = A_cpu @ B_cpu
end = time.time()
print(f"🧠 CPU matmul time: {end - start:.6f} sec")

# GPU matmul
device = "cuda" if torch.cuda.is_available() else "mps"
A_gpu = A_cpu.to(device)
B_gpu = B_cpu.to(device)

torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()

start = time.time()
result = A_gpu @ B_gpu
torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()
end = time.time()
print(f"⚡ GPU matmul time: {end - start:.6f} sec")
```

### 🧪 B. Element-wise Multiply: GPU vs CPU

```python
# CPU multiply
start = time.time()
result = A_cpu * B_cpu
end = time.time()
print(f"🧠 CPU element-wise time: {end - start:.6f} sec")

# GPU multiply
start = time.time()
result = A_gpu * B_gpu
torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()
end = time.time()
print(f"⚡ GPU element-wise time: {end - start:.6f} sec")
```

---

## 🧠 Why was your result strange?

### Because:

1. **we used matmul on GPU (O(n³)) vs element-wise on CPU (O(n))**  
   → Matmul is just much heavier by nature.

2. **MPS backend (Apple Silicon)** is still not as optimized as CUDA for heavy matmul.  
   → Especially true for large matrix sizes.

3. **macOS MPS has no async execution detection like CUDA**  
   → `.mps.synchronize()` helps but may not always sync perfectly in Jupyter timing.

---

## ✅ What to remember:

| To compare fairly | Use same operation | On both CPU & GPU |
|-------------------|--------------------|--------------------|
| Compare `@` vs `@`| For matrix timing   |                    |
| Compare `*` vs `*`| For element-wise    |                    |



In [188]:
# 🧪 A. Matrix Multiplication: GPU vs CPU
import torch
import time

size = 4000  # careful! 10000 x 10000 may crash CPU RAM

A_cpu = torch.rand(size, size)
B_cpu = torch.rand(size, size)

# CPU matmul
start = time.time()
result = A_cpu @ B_cpu
end = time.time()
print(f"🧠 CPU matmul time: {end - start:.6f} sec")

# GPU matmul
device = "cuda" if torch.cuda.is_available() else "mps"
A_gpu = A_cpu.to(device)
B_gpu = B_cpu.to(device)

torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()

start = time.time()
result = A_gpu @ B_gpu
torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()
end = time.time()
print(f"⚡ GPU matmul time: {end - start:.6f} sec")


🧠 CPU matmul time: 0.078821 sec
⚡ GPU matmul time: 0.051655 sec


### 🔑 The above seems to be wrong because size=4000 is `too small`

In [189]:
# 🧪 A. Matrix Multiplication: GPU vs CPU
import torch
import time

size = 20000  # careful! 10000 x 10000 may crash CPU RAM

A_cpu = torch.rand(size, size)
B_cpu = torch.rand(size, size)

# CPU matmul
start = time.time()
result = A_cpu @ B_cpu
end = time.time()
print(f"🧠 CPU matmul time: {end - start:.6f} sec")

# GPU matmul
device = "cuda" if torch.cuda.is_available() else "mps"
A_gpu = A_cpu.to(device)
B_gpu = B_cpu.to(device)

torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()

start = time.time()
result = A_gpu @ B_gpu
torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()
end = time.time()
print(f"⚡ GPU matmul time: {end - start:.6f} sec")


KeyboardInterrupt: 

In [ ]:
# 🧪 A. Matrix Multiplication: GPU vs CPU
import torch
import time

size = 10000  # careful! 10000 x 10000 may crash CPU RAM

A_cpu = torch.rand(size, size)
B_cpu = torch.rand(size, size)

# CPU matmul
start = time.time()
result = A_cpu @ B_cpu
end = time.time()
print(f"🧠 CPU matmul time: {end - start:.6f} sec")

# GPU matmul
device = "cuda" if torch.cuda.is_available() else "mps"
A_gpu = A_cpu.to(device)
B_gpu = B_cpu.to(device)

torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()

start = time.time()
result = A_gpu @ B_gpu
torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()
end = time.time()
print(f"⚡ GPU matmul time: {end - start:.6f} sec")


🧠 CPU matmul time: 1.152387 sec
⚡ GPU matmul time: 0.825128 sec


In [ ]:
# 🧪 B. Element-wise Multiply: GPU vs CPU

# CPU multiply
start = time.time()
result = A_cpu * B_cpu
end = time.time()
print(f"🧠 CPU element-wise time: {end - start:.6f} sec")

# GPU multiply
start = time.time()
result = A_gpu * B_gpu
torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()
end = time.time()
print(f"⚡ GPU element-wise time: {end - start:.6f} sec")


🧠 CPU element-wise time: 0.040624 sec
⚡ GPU element-wise time: 0.062440 sec


In [ ]:
# 🧪 A. Matrix Multiplication: GPU vs CPU
import torch
import time

size = 10000  # careful! 10000 x 10000 may crash CPU RAM

A_cpu = torch.rand(size, size)
B_cpu = torch.rand(size, size)

# CPU matmul
start = time.time()
result = A_cpu @ B_cpu
end = time.time()
print(f"🧠 CPU matmul time: {end - start:.6f} sec")

# GPU matmul
device = "cuda" if torch.cuda.is_available() else "mps"
A_gpu = A_cpu.to(device)
B_gpu = B_cpu.to(device)

torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()

start = time.time()
result = A_gpu @ B_gpu
torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()
end = time.time()
print(f"⚡ GPU matmul time: {end - start:.6f} sec")


# 🧪 B. Element-wise Multiply: GPU vs CPU

# CPU multiply
start = time.time()
result = A_cpu * B_cpu
end = time.time()
print(f"🧠 CPU element-wise time: {end - start:.6f} sec")

# GPU multiply
start = time.time()
result = A_gpu * B_gpu
torch.cuda.synchronize() if device == "cuda" else torch.mps.synchronize()
end = time.time()
print(f"⚡ GPU element-wise time: {end - start:.6f} sec")


🧠 CPU matmul time: 1.117793 sec
⚡ GPU matmul time: 0.832834 sec
🧠 CPU element-wise time: 0.030282 sec
⚡ GPU element-wise time: 0.008068 sec


### 🔑 Now this makes lots of sense

---
### Setting Time

#### 🕒 Summary of Timing Methods

| Method       | Scope           | Use Case                        | Output                      |
|--------------|------------------|----------------------------------|-----------------------------|
| `time.time()`| Python (standard)| Custom timing for code blocks   | Seconds (float)             |
| `%%time`     | Jupyter magic    | Time the **entire cell once**   | Wall time & CPU time shown |
| `%%timeit`   | Jupyter magic    | Time the cell **multiple times**, auto-averaged | Best of N runs (stats)     |

---

##### 🔍 `%%time` vs `%%timeit`

| Feature        | `%%time`                | `%%timeit`                    |
|----------------|-------------------------|-------------------------------|
| Runs           | 1                       | Many (auto-determined)        |
| Output         | One-time duration       | Average + std dev             |
| Overhead       | None                    | Slight (due to multiple runs) |
| Use for        | Rough profiling         | Micro-benchmarking            |

---

#### 🧰 Timer Decorator (for any function)

You can use this to time any Python function:

```python
import time
from functools import wraps

def timer(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"⏱️ Function '{func.__name__}' executed in {end - start:.6f} sec")
        return result
    return wrapper
```

##### 🧪 Example usage:

```python
@timer
def slow_function():
    total = 0
    for i in range(10**7):
        total += i
    return total

slow_function()
```

#### 1. `@timer_time` based on `time.time()` (custom Python)

In [ ]:
import time
from functools import wraps

def timer_time(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        # print(f"elapsed_time = {end - start:.8f}")
        print(f"[timer_time] '{func.__name__}' executed in {end - start:.8f} sec")
        return result
    return wrapper
    

# Example usage
@timer_time
def loop_sum():
    return sum(i for i in range(10**6))
    
loop_sum()  # In Jupyter, the final stmt in a cell will be printed

[timer_time] 'loop_sum' executed in 0.03027511 sec


499999500000

#### If we `don't want to return a value at the end stmt` of Jupyter cell:

In [ ]:
_= loop_sum()

[timer_time] 'loop_sum' executed in 0.02570796 sec


#### 2. `@timer_cell` -- simulating `%%time` for full function  (wall time + CPU time)

> - `wall time` = `time.time()` and is the clock (on the wall) time, which is the time you feel, the total time spent
> - `ru_utime` (retrieved from `resources`'s `SELF` for this specific program), is the time that this program acutually executed the CPU instructions

In [ ]:
import time
import resource
from functools import wraps

def timer_cell(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        start_wall = time.time()
        start_cpu = resource.getrusage(resource.RUSAGE_SELF).ru_utime
        # start_res = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        
        result = func(*args, **kwargs)
        
        end_wall = time.time()
        end_cpu = resource.getrusage(resource.RUSAGE_SELF).ru_utime
        # end_res = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        
        wall_time = end_wall - start_wall
        cpu_time = end_cpu - start_cpu
        
        # elapsed_cpu = end_cpu - start_cpu
        # elapsed_res = end_res - start_res
        
        print(f"wall time = {wall_time:.8f}")
        print(f"cpu_time  = {cpu_time:.8f}")
        return result
    
    return wrapper

# Example usage
@timer_cell
def list_comprehension():
    return [i**2 for i in range(10**6)]

_ = list_comprehension()

wall time = 0.03859687
cpu_time  = 0.03379300


In [ ]:
import time
import resource
from functools import wraps

def timer_cell(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        start_wall = time.time()
        start_cpu = resource.getrusage(resource.RUSAGE_SELF).ru_utime
        result = func(*args, **kwargs)
        end_wall = time.time()
        end_cpu = resource.getrusage(resource.RUSAGE_SELF).ru_utime
        print(f"[timer_cell] '{func.__name__}' wall time: {end_wall - start_wall:.6f} sec")
        print(f"[timer_cell] '{func.__name__}' CPU time:  {end_cpu - start_cpu:.6f} sec")
        return result
    return wrapper

# Example usage
@timer_cell
def list_comprehension():
    return [i**2 for i in range(10**6)]

_ = list_comprehension()


[timer_cell] 'list_comprehension' wall time: 0.043481 sec
[timer_cell] 'list_comprehension' CPU time:  0.034716 sec


In [ ]:
# some other example for sleep(2) to make difference of wall/cpu time

import time

def sleepy():
    time.sleep(2)
    return sum(range(10**6))

sleepy()

499999500000

In [ ]:
import time

@timer_cell
def sleepy():
    time.sleep(2)
    return sum(range(10**6))

sleepy()

[timer_cell] 'sleepy' wall time: 2.017744 sec
[timer_cell] 'sleepy' CPU time:  0.013933 sec


499999500000

#### 3. `@timer_timeit` -- Mimicking `%%timeit` using `timeit.repeat()`

In [ ]:
import timeit
from functools import wraps

def timer_timeit(n=5, r=3):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            stmt = lambda: func(*args, **kwargs)
            times = timeit.repeat(stmt, repeat=r, number=n)
            best_time = min(times) / n
            print(f"[timer_timeit] '{func.__name__}' best of {r} × {n} runs: {best_time:.6f} sec/run")
            return func(*args, **kwargs)
        return wrapper
    return  decorator

# Example usage
@timer_timeit(n=3, r=5)
def multiply_loop():
    x = 1
    for i in range(1, 10000):
        x *= 1
    return x

multiply_loop()

[timer_timeit] 'multiply_loop' best of 5 × 3 runs: 0.000155 sec/run


1

In [ ]:
import timeit
from functools import wraps
import statistics  ## for calc mean and median times

def timer_timeit(n=5, r=3):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            stmt = lambda: func(*args, **kwargs)
            times = timeit.repeat(stmt, repeat=r, number=n)
            
            best_time = min(times) / n
            worst_time = max(times) / n
            avg_time = statistics.mean(times) / n
            median_time = statistics.median(times) / n
            
            print(f"[timer_timeit] '{func.__name__}' best    of {r} × {n} runs: {best_time:.6f} sec/run")
            print(f"[timer_timeit] '{func.__name__}' worst   of {r} × {n} runs: {worst_time:.6f} sec/run")
            print(f"[timer_timeit] '{func.__name__}' average of {r} × {n} runs: {avg_time:.6f} sec/run")
            print(f"[timer_timeit] '{func.__name__}' median  of {r} × {n} runs: {median_time:.6f} sec/run")
            return func(*args, **kwargs)
        return wrapper
    return  decorator

# Example usage
@timer_timeit(n=20, r=30)
def multiply_loop():
    x = 1
    for i in range(1, 10000):
        x *= 1
    return x

multiply_loop()

[timer_timeit] 'multiply_loop' best    of 30 × 20 runs: 0.000146 sec/run
[timer_timeit] 'multiply_loop' worst   of 30 × 20 runs: 0.000310 sec/run
[timer_timeit] 'multiply_loop' average of 30 × 20 runs: 0.000177 sec/run
[timer_timeit] 'multiply_loop' median  of 30 × 20 runs: 0.000153 sec/run


1

---
## %%time and some torch operations

In [ ]:
import torch
import numpy as np
import time

device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
print(device)

mps


In [190]:
%%time
start = time.time()

# matrix operation here
zeros = torch.zeros(1, 1)

end = time.time()

elapse = end - start
print(f"elapse = {elapse:.6f}")

elapse = 0.001039
CPU times: user 508 μs, sys: 1.27 ms, total: 1.78 ms
Wall time: 1.17 ms


### PyTorch Operations

| Function                      | Main Purpose                          |
|------------------------------|----------------------------------------|
| `torch.stack`                | Stack tensors along a **new dimension** |
| `torch.cat`                  | Concatenate tensors along an **existing dimension** |
| `torch.multinomial`          | Sample based on given probabilities     |
| `torch.tril` / `torch.triu`  | Extract lower / upper triangular matrix |
| `input.T` / `transpose`      | Transpose a tensor (2D or more needs2use `transpose`)         |
| `nn.Linear`                  | Create a fully connected (linear) layer |
| `F.softmax`                  | Convert logits to probabilities         |


In [ ]:
# torch.stack, torch.multinomial, torch.trill, torch.trilu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax

#### `torch.stack(tensors, dim=0)`

In [191]:
# torch.stack(tensors, dim=0)

import torch

a = torch.tensor([1, 2])
b = torch.tensor([3, 4])

stacked = torch.stack([a, b],  dim=0)

stacked

tensor([[1, 2],
        [3, 4]])

In [193]:
torch.stack([a, b], dim=1)

tensor([[1, 3],
        [2, 4]])

#### `torch.cat` - use this to generating text giving the context
- adding the predicted word and concatenate to the current chunk of words

In [216]:
tensor = torch.tensor([1, 2, 3, 4,])
out = torch.cat((tensor, torch.tensor([5, 6])), 0)

out

tensor([1, 2, 3, 4, 5, 6])

####  `torch.multinomial(input, num_samples, replacement=False)`
`we will use this to predict what word will come next 我們用這來預測下一個字`

In [195]:
# Torch.multinomial(input, num_samples, replacement=False)
# Sampling based on given probability (根據給定的機率分佈進行抽樣)

# [index]：probability -> [0]:0.1, [1]:0.3, [2]:0.6
weights = torch.tensor([0.1, 0.3, 0.6])  # this is the given prob

samples = torch.multinomial(weights, 5, replacement=True)
print(samples)


tensor([2, 2, 2, 0, 1])


In [200]:
weights = torch.tensor([0.1, 0.3, 0.6])

samples = torch.multinomial(weights, 100, replacement=True)

# use bincount to calc the freq of each digits
counts = torch.bincount(samples)
print(f"Count of index 0: {counts[0]}, dist P: {counts[0] / 100:.2f}")
print(f"Count of index 1: {counts[1]}, dist P: {counts[1] / 100:.2f}")
print(f"Count of index 2: {counts[2]}, dist P: {counts[2] / 100:.2f}")

Count of index 0: 5, dist P: 0.05
Count of index 1: 41, dist P: 0.41
Count of index 2: 54, dist P: 0.54


#### 3. `torch.trill(input, diagonal=0)` and `triu(input, diagonal=0)`

In [203]:
x = torch.arange(1, 37).reshape(6, 6)
print(torch.tril(x))

tensor([[ 1,  0,  0,  0,  0,  0],
        [ 7,  8,  0,  0,  0,  0],
        [13, 14, 15,  0,  0,  0],
        [19, 20, 21, 22,  0,  0],
        [25, 26, 27, 28, 29,  0],
        [31, 32, 33, 34, 35, 36]])


In [204]:
x = torch.arange(1, 37).reshape(6, 6)
torch.triu(x)


tensor([[ 1,  2,  3,  4,  5,  6],
        [ 0,  8,  9, 10, 11, 12],
        [ 0,  0, 15, 16, 17, 18],
        [ 0,  0,  0, 22, 23, 24],
        [ 0,  0,  0,  0, 29, 30],
        [ 0,  0,  0,  0,  0, 36]])

#### `input.T` vs `input.transpose(dim0, dim1)`

In [205]:
x = torch.randn(2, 3)
x

tensor([[ 0.9166,  0.4310, -0.5345],
        [-0.1544,  0.1354, -0.7043]])

In [206]:
x = torch.randn(2, 3)
print(x.T)

tensor([[ 0.3581, -0.2482],
        [-0.5619, -0.3787],
        [-0.8063,  0.5485]])


In [ ]:
x3d = torch.randn(2, 3, 4)
print(x3d.transpose(1, 2).shape) # 1 means index 1 => 3, 2 means index 2 => 4

# therefore, x3d = (2, 3, 4) -> (2, 4, 3)

torch.Size([2, 4, 3])


#### `nn.Linear(in_features, out_features)`

In [ ]:
import torch.nn as nn

layer = nn.Linear(4, 2)    # y = xW^T + b => in: 4, out: 2
input = torch.randn(3, 4)  # (batch_size :3 , in_features: 4)
output = layer(input)

output.shape

torch.Size([3, 2])

In [212]:
input.shape

torch.Size([3, 4])

In [213]:
layer = nn.Linear(4, 2)  # in_features: 4, out_features: 2
x = torch.rand(32, 4)  # 32 samples (batch size=32), each w/4 features
output = layer(x)
print(output.shape)


torch.Size([32, 2])


| concept            | description                                       |
|------------------|--------------------------------------------|
| `nn.Linear(m, n)`| convert each data item from m dim to n dim    |
| `x.shape`        | must be `[batch_size, in_features]`          |
| `output.shape`   | result will be `[batch_size, out_features]`       |
| `batch size`     | concurrent process multi-data, faster, stable gradient     |

#### 7. `F.softmax` : convert `logits` into `softmax` probs. (sum up to 1)

In [214]:
import torch.nn.functional as F

x = torch.tensor([1.0, 2.0, 3.0, 4.0])
probs = F.softmax(x, dim=0)

probs

tensor([0.0321, 0.0871, 0.2369, 0.6439])